### PR TITLE
dumb shell script client

### PR DESCRIPTION
**Pull request by sstjohn**
for your consideration

### CODE REVIEW

**Comment by iangreenleaf** [comment]
Closing this. Brute-forcing the Plans interface to dig for information is not a great thing to do. I'm not sure if the ToS explicitly forbids this, but at the very least I'm sure the admins would frown upon it.

/cc @acohn

**Comment by sstjohn** [comment]
It's not really brute forcing anything-- that would be trying every string that could be a Plan name in sequence, like [aaaaaaaa], [aaaaaaab], [aaaaaaaac], etc. This is literally the equivalent of going through the directory and clicking on every link to see if the plan is visible, which is something that you could easily do by hand, albeit way slower. I suppose it's most similar to a spider, although it doesn't try to retrieve any content; it's just checking for an API error.

Anyway I talked to Alex once about rate-limiting with respect to a different client, and it doesn't sound to me like this is gonna be hugely taxing on the servers if it's only being run once in a while. That said, I'd be happy to add some delays or whatever in the interest of keeping the server load minimal. :-)

**Comment by iangreenleaf** [comment]
You and I both know that this exists in a gray zone of something that is theoretically possible to do by hand, but in practical terms infeasible without automation. It's certainly not behavior I'm going to encourage. The bottom line is this: the Plans ToS prohibits making automated requests to the servers with a client that has not been approved by the administrators. Unless you have secured approval, I would recommend that you (or anyone else) do not run this script. If you were to do so, the Plans admins would have grounds to punish you as they see fit.

**Comment by sstjohn** [comment]
Funny, I can't find any list of "approved" clients. Is Firefox? How about
lynx? Why not curl?

**Comment by iangreenleaf** [comment]
Saul, I know you'd love to get into a long pointless argument, but I'm not going to do it. I think I've made myself clear, and I don't think there's anything to be learned from further discussion on this issue, so I'm going to close the discussion.

**Pull request closed without merging**
